apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michael-git-repo/k8-microservices.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
